print_mg=(print("☄️Starting Your Task......"),
print("⚡Collecting Variables......"),
print("🚀updating Database........."),
print("🔥Collecting Workers........."),
print("🎀Connecting Epic Devs Ai......"),
print("🎀 Successfully Connected EPIC AI🎀"),
print("EPIC BOTS🇱🇰"),
print("🚀loading....."),
print("⚡Get variables.."),
print("🛠️Chekin latest Version...."),
print("🔥Your Bot Successfuly Deployed!.."),
print("🏅chek For Updates @EpicBotsSl"))
