print("☄️Starting Your Task......"),
print("⚡Collecting Variables......"),
print("🚀updating Database........."),
print("🔥Collecting Workers........."),
print("🎀Connecting Epic Devs Ai......"),
print("🎀 Successfully Connected EPIC AI🎀"),
